<a href="https://colab.research.google.com/github/mrsferret/Code-Division/blob/main/Worksheets/Numpy_mini_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Investigate, wrangle, add new data to the dataframe, filter and correlate

The following data file contains data about student scores in math, reading and writing.  The exam scores are assumed to be percentages. It also contains data about gender, ethnicity, parental education, whether the student qualifies for free school food and whether or not the student has taken a preparation course for the exams.  The data set has already been cleaned. 

1.  Investigate the data set.

2.  Create numpy arrays to hold each of the three sets of scores.  
Create a new numpy array to hold the average exam score (of the three scores for each student)
Add the new numpy array as a new column in the dataframe.

3.  Filter the original dataset into a new dataframe containing just the females.  Calculate the average exam scores for all rows in this new dataframe and then find the mean of the average column.

4.  Do the same for the males.

5.  Use the original dataset to find the correlation coefficient for reading and maths.  How closely do they correlate?  Write what you find in a text box below the code.

6.  Do the same for reading and writing. What do you find?

7.  You might want to filter on different criteria and check correlation (e.g. those on free school meals, or those who had prepared, etc)







The dataset can be accessed here:  https://raw.githubusercontent.com/lilaceri/Working-with-data-/main/Data%20Sets%20for%20code%20divisio/exams.csv.  This is a .csv file.

**NOTE:** Some useful references are included at the bottom of this spreadsheet.

Use the code cell below to work your code.

In [ ]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/lilaceri/Working-with-data-/main/Data%20Sets%20for%20code%20divisio/exams.csv"
df = pd.read_csv(url)
#df.info()
print (df.head())


math_score_np = df['math_score'].to_numpy(np.int32)
reading_score_np = df['reading_score'].to_numpy(np.int32)
writing_score_np = df['writing_score'].to_numpy(np.int32)

#=======================================================
# Create single array from the 3 separate arrays
#=======================================================
arr = np.array([[math_score_np], 
               [reading_score_np],
                [writing_score_np]])
#arr = np.array([math_score_np, 
#          reading_score_np,
#          writing_score_np])
display(arr)

#=======================================================
# Calculate average score for each student 
#=======================================================
arr2 = np.round(((np.sum(arr,axis=0))/3))

display ('Overall Mean Scores: ', arr2)

#====================================================================
# Add the Overall Average as a new column to original dataframe
#================================================================
#df['Overall Average'] = arr2.tolist()
df['Overall Average'] = arr2

#=======================================================
# Filter just females from original dataset
#=========================================================

filtered_df = df[df['gender'] == 'female'] 


#filtered_df = df[df['gender' == 'female']]
#filtered_df = df.filter(like='female', axis=0)
print ('Filtered df: ', filtered_df)

#=======================================================
# find the correlation coefficient for reading and maths
#=======================================================
coef = np.corrcoef(reading_score_np, math_score_np)
print('Coef of reading and maths scores: ', coef) 

#=======================================================
# find the correlation coefficient for reading and maths
#=======================================================
coef = np.corrcoef(reading_score_np, writing_score_np)
print('Coef of reading and writing scores: ', coef) 



   gender ethnicity  ... reading_score writing_score
0  female   group E  ...            76            71
1    male   group C  ...            72            69
2  female   group B  ...            56            61
3    male   group D  ...            60            59
4  female   group C  ...            54            55

[5 rows x 8 columns]


array([[[65, 75, 62, ..., 65, 62, 38]],

       [[76, 72, 56, ..., 94, 62, 39]],

       [[71, 69, 61, ..., 93, 57, 40]]], dtype=int32)

'Overall Mean Scores: '

array([[ 71.,  72.,  60.,  60.,  48.,  60.,  88.,  79.,  64.,  81.,  90.,
         64.,  39.,  84.,  49.,  62.,  66.,  58.,  49.,  77.,  76.,  36.,
         79.,  82.,  67.,  57.,  66.,  43.,  89.,  82.,  61.,  76.,  67.,
         79.,  79.,  96.,  73.,  57.,  80.,  80.,  86.,  60.,  60.,  97.,
         68.,  80.,  89.,  68.,  53.,  61.,  79.,  69.,  91.,  61.,  68.,
         65.,  70.,  70.,  71.,  92.,  78.,  81.,  42.,  63.,  46.,  78.,
         61.,  72.,  94.,  58.,  90.,  70.,  60.,  76.,  69.,  73.,  87.,
         95.,  40.,  81.,  80.,  72.,  58.,  86.,  53.,  90.,  22.,  90.,
         56.,  59.,  98.,  51.,  45.,  73.,  72.,  56.,  65.,  83.,  87.,
         72.,  57.,  92.,  81.,  74.,  87.,  53.,  78.,  63.,  79.,  67.,
         59.,  50.,  59.,  71.,  71.,  65.,  69.,  64.,  62.,  54.,  54.,
         47.,  67.,  64.,  62.,  56.,  59.,  69.,  66.,  49.,  57.,  71.,
         64.,  90.,  54.,  70.,  73.,  61.,  50.,  71.,  79.,  37.,  81.,
         77.,  58.,  84.,  86.,  76., 

ValueError: ignored

In [21]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/lilaceri/Working-with-data-/main/Data%20Sets%20for%20code%20divisio/exams.csv"
df = pd.read_csv(url)
#df.info()'
print (df.head())
print ('Columns: ', df.columns)

math_score_np = df['math_score'].to_numpy(np.int32)
reading_score_np = df['reading_score'].to_numpy(np.int32)
writing_score_np = df['writing_score'].to_numpy(np.int32)

#=======================================================
# Create single array from the 3 separate arrays
#=======================================================
arr = np.array([math_score_np, 
          reading_score_np,
          writing_score_np])
display(arr)

#=======================================================
# Calculate average score for each student 
#=======================================================
arr2 = np.round(((np.sum(arr,axis=0))/3))

display ('Overall Mean Scores: ', arr2)

#====================================================================
# Add the Overall Average as a new column to original dataframe
#================================================================
#df['Overall Average'] = arr2.tolist()
df['Overall Average'] = arr2

#=======================================================
# Filter just females from original dataset
#=========================================================

filtered_df = df[df['gender'] == 'female'] 

#filtered_df = df[df['gender' == 'female']]
#filtered_df = df.filter(like='female', axis=0)
print ('Filtered df: ', filtered_df)

#======================================================
# Now calculate the average score for females
#======================================================

fem_math_score_np = filtered_df['math_score'].to_numpy(np.int32)
fem_reading_score_np = filtered_df['reading_score'].to_numpy(np.int32)
fem_writing_score_np = filtered_df['writing_score'].to_numpy(np.int32)

#=======================================================
# Create single array from the 3 separate arrays
#=======================================================
fem_arr = np.array([fem_math_score_np, 
                    fem_reading_score_np,
                    fem_writing_score_np])
display(fem_arr)

#=======================================================
# Calculate average score for each female student 
#=======================================================
fem_arr2 = np.round(((np.sum(fem_arr,axis=0))/3))

display ('Overall Mean Scores for each female student: ', fem_arr2)

#compute mean
overall_fem_mean = np.round(np.mean(fem_arr2))
display ("Overall Mean for all Female Students: ", overall_fem_mean)

#=======================================================
# Filter just males from original dataset
#=========================================================

filtered_df = df[df['gender'] == 'male'] 

#filtered_df = df[df['gender' == 'male']]
#filtered_df = df.filter(like='male', axis=0)
print ('Filtered df: ', filtered_df)

#======================================================
# Now calculate the average score for females
#======================================================

male_math_score_np = filtered_df['math_score'].to_numpy(np.int32)
male_reading_score_np = filtered_df['reading_score'].to_numpy(np.int32)
male_writing_score_np = filtered_df['writing_score'].to_numpy(np.int32)

#=======================================================
# Create single array from the 3 separate arrays
#=======================================================
male_arr = np.array([male_math_score_np, 
                    male_reading_score_np,
                    male_writing_score_np])
display(male_arr)

#=======================================================
# Calculate average score for each female student 
#=======================================================
male_arr2 = np.round(((np.sum(male_arr,axis=0))/3))

display ('Overall Mean Scores for each male student: ', male_arr2)

#compute mean
overall_male_mean = np.round(np.mean(male_arr2))
display ("Overall Mean for all Male Students: ", overall_male_mean)

# Calculates correlation coefficient
def calc_corr_coef(score1_np, score2_np):
  coef = np.round(np.corrcoef(score1_np, score2_np),4)
  print(coef)
  return coef

#=======================================================
# find the correlation coefficient for reading and maths
#======================================================
coef = calc_corr_coef(math_score_np, reading_score_np)
print ('Correlation Coefficient for reading and maths: ', coef[0][1])

#=======================================================
# find the correlation coefficient for reading and writing
#======================================================
coef = calc_corr_coef(reading_score_np, writing_score_np)
print ('Correlation Coefficient for reading and writing: ', coef[0][1])

#=======================================================
# find the correlation coefficient for maths and writing
#======================================================
coef = calc_corr_coef(math_score_np, writing_score_np)
print ('Correlation Coefficient for maths and writing: ', coef[0][1])
    
#=======================================================
# find the correlation coefficient for maths and lunch
#======================================================

    

   gender ethnicity  ... reading_score writing_score
0  female   group E  ...            76            71
1    male   group C  ...            72            69
2  female   group B  ...            56            61
3    male   group D  ...            60            59
4  female   group C  ...            54            55

[5 rows x 8 columns]
Columns:  Index(['gender', 'ethnicity', 'parental_education', 'lunch',
       'preparation_course', 'math_score', 'reading_score', 'writing_score'],
      dtype='object')


array([[65, 75, 62, ..., 65, 62, 38],
       [76, 72, 56, ..., 94, 62, 39],
       [71, 69, 61, ..., 93, 57, 40]], dtype=int32)

'Overall Mean Scores: '

array([ 71.,  72.,  60.,  60.,  48.,  60.,  88.,  79.,  64.,  81.,  90.,
        64.,  39.,  84.,  49.,  62.,  66.,  58.,  49.,  77.,  76.,  36.,
        79.,  82.,  67.,  57.,  66.,  43.,  89.,  82.,  61.,  76.,  67.,
        79.,  79.,  96.,  73.,  57.,  80.,  80.,  86.,  60.,  60.,  97.,
        68.,  80.,  89.,  68.,  53.,  61.,  79.,  69.,  91.,  61.,  68.,
        65.,  70.,  70.,  71.,  92.,  78.,  81.,  42.,  63.,  46.,  78.,
        61.,  72.,  94.,  58.,  90.,  70.,  60.,  76.,  69.,  73.,  87.,
        95.,  40.,  81.,  80.,  72.,  58.,  86.,  53.,  90.,  22.,  90.,
        56.,  59.,  98.,  51.,  45.,  73.,  72.,  56.,  65.,  83.,  87.,
        72.,  57.,  92.,  81.,  74.,  87.,  53.,  78.,  63.,  79.,  67.,
        59.,  50.,  59.,  71.,  71.,  65.,  69.,  64.,  62.,  54.,  54.,
        47.,  67.,  64.,  62.,  56.,  59.,  69.,  66.,  49.,  57.,  71.,
        64.,  90.,  54.,  70.,  73.,  61.,  50.,  71.,  79.,  37.,  81.,
        77.,  58.,  84.,  86.,  76.,  97.,  62.,  5

Filtered df:       gender ethnicity  ... writing_score Overall Average
0    female   group E  ...            71            71.0
2    female   group B  ...            61            60.0
4    female   group C  ...            55            48.0
5    female   group B  ...            61            60.0
6    female   group D  ...            92            88.0
..      ...       ...  ...           ...             ...
989  female   group D  ...            82            77.0
991  female   group C  ...            77            74.0
992  female   group C  ...            65            58.0
994  female   group D  ...            80            75.0
997  female   group C  ...            93            84.0

[496 rows x 9 columns]


array([[65, 62, 34, ..., 46, 72, 65],
       [76, 56, 54, ..., 62, 74, 94],
       [71, 61, 55, ..., 65, 80, 93]], dtype=int32)

'Overall Mean Scores for each female student: '

array([ 71.,  60.,  48.,  60.,  88.,  64.,  90.,  64.,  39.,  49.,  62.,
        66.,  49.,  77.,  36.,  79.,  82.,  89.,  82.,  76.,  67.,  79.,
        96.,  73.,  57.,  80.,  80.,  86.,  60.,  60.,  97.,  68.,  89.,
        69.,  68.,  70.,  70.,  71.,  78.,  63.,  61.,  94.,  58.,  60.,
        76.,  87.,  95.,  81.,  72.,  53.,  90.,  98.,  73.,  72.,  83.,
        72.,  81.,  74.,  87.,  78.,  63.,  79.,  59.,  65.,  69.,  54.,
        62.,  59.,  69.,  66.,  49.,  57.,  90.,  73.,  61.,  50.,  79.,
        81.,  77.,  58.,  84.,  86.,  97.,  58.,  72.,  76.,  74.,  63.,
        82.,  97.,  53.,  56.,  89.,  93.,  64.,  91.,  82.,  79.,  87.,
        75.,  75.,  53.,  64.,  68.,  83.,  75.,  52.,  60.,  72.,  64.,
        63.,  55.,  59.,  70.,  90.,  78.,  67.,  70.,  81.,  72.,  84.,
        83.,  71.,  84.,  74.,  74.,  94.,  81.,  82.,  57.,  79.,  83.,
        57.,  87.,  75.,  75.,  65.,  60.,  70.,  82.,  64.,  54.,  60.,
        57.,  61., 100.,  56.,  52.,  79.,  78.,  5

'Overall Mean for all Female Students: '

71.0

Filtered df:      gender ethnicity  ... writing_score Overall Average
1     male   group C  ...            69            72.0
3     male   group D  ...            59            60.0
7     male   group E  ...            70            79.0
9     male   group C  ...            82            81.0
13    male   group C  ...            81            84.0
..     ...       ...  ...           ...             ...
993   male   group E  ...            69            75.0
995   male   group B  ...            74            76.0
996   male   group D  ...            82            84.0
998   male   group B  ...            57            60.0
999   male   group B  ...            40            39.0

[504 rows x 9 columns]


array([[75, 60, 93, ..., 82, 62, 38],
       [72, 60, 73, ..., 87, 62, 39],
       [69, 59, 70, ..., 82, 57, 40]], dtype=int32)

'Overall Mean Scores for each male student: '

array([ 72.,  60.,  79.,  81.,  84.,  58.,  76.,  67.,  57.,  66.,  43.,
        61.,  79.,  80.,  68.,  53.,  61.,  79.,  91.,  61.,  65.,  92.,
        81.,  42.,  46.,  78.,  72.,  90.,  70.,  69.,  73.,  40.,  80.,
        58.,  86.,  90.,  22.,  56.,  59.,  51.,  45.,  56.,  65.,  87.,
        57.,  92.,  53.,  67.,  59.,  50.,  71.,  71.,  64.,  62.,  54.,
        47.,  67.,  64.,  56.,  71.,  64.,  54.,  70.,  71.,  37.,  76.,
        62.,  73.,  44.,  61.,  76.,  81.,  51.,  42.,  61.,  31.,  89.,
        74.,  41.,  53.,  59.,  90.,  72.,  64.,  99.,  69.,  45.,  44.,
        33.,  81.,  79.,  73.,  88.,  57.,  29.,  56.,  50.,  74.,  61.,
        57.,  51.,  58.,  78.,  75.,  66.,  75.,  61.,  68.,  82.,  61.,
        79.,  69.,  60.,  55.,  77.,  52.,  42.,  55.,  79.,  45.,  62.,
        45.,  87.,  59.,  63.,  56.,  76.,  68.,  71.,  60.,  49.,  83.,
        33.,  60.,  92.,  37.,  40.,  89.,  42.,  58.,  46.,  75.,  74.,
        49.,  46.,  78.,  70.,  89.,  46.,  89.,  9

'Overall Mean for all Male Students: '

66.0

[[1.     0.8146]
 [0.8146 1.    ]]
Correlation Coefficient for reading and maths:  0.8146
[[1.     0.9568]
 [0.9568 1.    ]]
Correlation Coefficient for reading and writing:  0.9568
[[1.     0.8088]
 [0.8088 1.    ]]
Correlation Coefficient for maths and writing:  0.8088


ValueError: ignored

### Helpful references
---

Filtering on criteria using df references:  
`filtered_df = df[df['column name' == value]]`  

Filtering on multiple criteria using df reference:  
`filtered_df = df[df['first column name' == value] & df[second column name] >= value]`

Numpy help sheet:  http://datacamp-community-prod.s3.amazonaws.com/da466534-51fe-4c6d-b0cb-154f4782eb54




---

# **What did I have difficulties with:**
I had a problem when adding the numpy array I created as a new column in the dataframe and got the following error:

```
ValueError: Length of values (1) does not match length of index (1000)
```

Turns out the problem occurred as a result of my code that created the single numpy array from the 3 separate ones. My original code was as follows:


```
arr = np.array([[math_score_np], 
               [reading_score_np],
                [writing_score_np]])

```
Basically had too many square brackets. I didn't need the brackets round each numpy array. By removing these and just leaving square brackets around the entire list as follows corrected the error when adding the numpy array as a new column on original dataframe:

```
arr = np.array([math_score_np, 
          reading_score_np,
          writing_score_np])e
```
The syntax for the example code for filtering is incorrect
The example given is:
```
filtered_df = df[df['column name' == value]]

```
But this didn't work when used in my code:

```
filtered_df = df[df['gender' == 'female']]
```
I had to change it to the following to work:

```
filtered_df = df[df['gender'] == 'female'] 
```





---

